# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sechouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sechousepirce',
            table='sec_house_price',
        ),
    ]
