# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sechouse', '0002_auto_20190914_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sechousepirce',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
    ]
